### ISSUE TITLE
Extension asking for test subject's consent 

### ISSUE THREAD

**Issue by loo242** [ristokitsing/EMS#24]
Risto, 
please, extend the extension's functionality so that it asks for a test subject's consent 
before starting a data tracking session (a separate consent for every session).

**Comment by ristokitsing** [comment]
Due to the way Chrome Extension API handles storage, I am not able to complete this within time (obvious by now).
Problem occurs when you query data with
```
chrome.storage.local.get('userHasAccepted, queryResult => {
  console.log(queryResult); //Gets the right value, like "true"
});
```
now, when you would want to `return` this value, you would get back a `Promise` event (because code has not evaluated yet, it's stuck in a `unresolved` state)! I would have to find a way to defer this and actually obtain a value *after* a `Promise` has been resolved.
